### ISSUE TITLE
Some of the apps crash

### ISSUE THREAD

**Issue by kingstonckt** [Litteeen/Rose#29] opened 2020-03-28 19:58 UTC
After turning ROSE on, some of the apps crash, such as snapchat, google photo, icleaner and some of the local bank apps. Thus, please add a function to blacklist apps from applying ROSE functions.

**Comment by Litteeen** [comment] 2020-03-31 15:47
i’m not going to add blacklisting, but you’re pretty much the only one to have that issue

Try if there’s something else causing it or at least provide a crash log

**Comment by Litteeen** [comment] 2020-03-31 15:48
Also this issue is a duplicate of an already existing one so i’ll close this one

**Closed by Litteeen** 2020-03-31 15:48 UTC
Labels: question
